### ISSUE TITLE
ComponentNotRegisteredException when running.

### ISSUE THREAD

**Issue by darrelmiller** [webapibook/issuetracker#14]
I get the following error,

The requested service 'WebApiBook.IssueTrackerApi.IssueHypermediaHandler' has not been registered.

 I tried registering it but ended up in a rat-hole because it's constructor takes a factory that cannot be resolved, and that factory has a dependency on IssueLinkFactory which needs a request message.  Not sure how we can instantiate a MessageHandler that has a dependency on a request message in its constructor.

**Comment by glennblock** [comment]
What branch are you cloning? You should be using Dev, which only has an API project (no host). Right now only integration tests work.

-----Original Message-----

**Comment by darrelmiller** [comment]
I'm looking at dev.  This https://github.com/webapibook/issuetracker/blob/dev/src/WebApiBook.IssueTrackerApi/App_Start/WebApiConfig.cs looks like a web host to me?

**Comment by glennblock** [comment]
That is left over. It won't work. I will cleanup the files.

-----Original Message-----

**Comment by darrelmiller** [comment]
ah, ok.  Gotcha.
